"""
MyApp
Auto-assembled by YAKSHA AI v2.0 Assembly Engine — do not edit by hand;
regenerate via the agent crew instead.
Dependencies: flask
"""

# --- Frontend markup (embedded verbatim by Assembly Engine) ---
FRONTEND_HTML = "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"UTF-8\">\n  <title>MyApp</title>\n  <script src=\"https://cdn.tailwindcss.com\"></script>\n</head>\n<body class=\"flex items-center justify-center h-screen bg-gray-100\">\n  <h1 id=\"message\" class=\"text-3xl font-semibold text-gray-800\">Loading...</h1>\n\n  <script>\n    document.addEventListener('DOMContentLoaded', function () {\n      fetch('/message')\n        .then(response => {\n          if (!response.ok) {\n            throw new Error('Network response was not ok');\n          }\n          return response.json();\n        })\n        .then(data => {\n          const heading = document.getElementById('message');\n          heading.textContent = data.message || 'No message';\n        })\n        .catch(error => {\n          const heading = document.getElementById('message');\n          heading.textContent = 'Error loading message';\n          console.error('Fetch error:', error);\n        });\n    });\n  </script>\n</body>\n</html>"

from flask import Flask, jsonify

app = Flask(__name__)


# --- Frontend route (injected by Assembly Engine) ---
@app.route("/")
def _yaksha_serve_frontend():
    return FRONTEND_HTML


# --- Entry point (generated by Assembly Engine) ---
if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=False)
